export const organisers: string[] = [
	'87seconds',
	'ACC (Association of Communication Companies)',
	'Acerta Consult',
	'ACRAI (UAntwerpen Center for Responsible AI)',
	'Actonomy',
	'ACV puls',
	'addData',
	'Adobe',
	'Adrem Data Lab (UAntwerpen)',
	'Advancing Analytics',
	'Advatera',
	'AG Insurance',
	'AG Solution Group',
	'Agentschap Binnenlands Bestuur',
	'Agifly',
	'Agora Marketing',
	'Agoria',
	'Agoya',
	'AI Campus',
	'AI Learning Academy',
	'AI Mindset',
	'AI Opportunity Fund, Centre for Public Impact',
	'AI Trainingen Vlaanderen',
	'AI, Media and Democracy Lab',
	'AI4Belgium',
	'AI4Culture',
	'AI4media',
	'AI5050',
	'AI@UHasselt',
	'AIDA',
	'AIdapt',
	'AIG',
	'AIG, Alumnivereniging Ingenieurs UGent',
	'Airobi',
	'aivancity',
	'Aivix',
	'Akkodis',
	'AKO Research',
	'Albert.AI by Zoomd',
	'Aleph Alpha',
	'Alfasent',
	'Algebra International School Croatia',
	'Algemene Rekenkamer',
	'Algoet Engineering',
	'ALLPha Academy for Lifelong Learning in Pharmacy (UGent)',
	'amai!',
	'Amazon Web Solutions (AWS)',
	'Amazone vzw',
	'AmeXio Group',
	'Anna Pops',
	'Annelies Verbeke',
	'Antrophic',
	'Ants Agency',
	'Ants Connect',
	'Antwerp Management School (AMS)',
	'AP Hogeschool',
	'Apache Arrow',
	'ARhus',
	'Art-up',
	'Arteveldehogeschool',
	'Ashoka',
	'Associatie UGent',
	'Association for Computational Linguistics (ACL)',
	'Association for Constraint Programming',
	'Association for Cultural Economics Poland',
	'Atlas College Genk',
	'Atos Worldline',
	'Avansa',
	'Awell health',
	'AZ Delta',
	'Azalea Vision',
	'Balboa Park Online Collaboration (BPOC)',
	'Bangalore University',
	'Barco',
	'BeCentral',
	'BeCode',
	'bedrijfsopleidingen.be',
	'Belga',
	'Belgian Association for Psychological Sciences (BAPS)',
	'Belgian Cockpit Association',
	'Beltug',
	'BEMAS',
	'Berenike Global Fashion Management',
	'BERLIN',
	'Better Minds at Work',
	'Beweging Academie',
	'Bibelieve',
	'Bibliotheek Wervik',
	'BigDat 2021A',
	'BimSem (Berthoutinstituut-Klein Seminarie)',
	'Bioethics Institute Ghent (BIG, UGent)',
	'BioLizard',
	'BioWin',
	'Birla Institute of Technology and Science, Pilani',
	'BlueCourses',
	'bnosac',
	'BNP Paribas Fortis',
	'Boostifai',
	'Borgerhoff & Lamberigts',
	'Boston Consulting Group (BCG)',
	'Brainjar',
	'Brainmove',
	'Brightbib',
	'Brightlab',
	'BrightWolves',
	'Brigit.vlaanderen',
	'British APCO',
	'Broadcom',
	'Bruegel',
	'Brussels Institute of Advanced Studies (BrIAS) (ULB & VUB)',
	'Buildwise',
	'Bureau Boone',
	'Buseloc',
	'Business Data Science',
	'C-Jay International',
	'Canva',
	'Capibara',
	'CC De Biekorf',
	'CC De Schakel',
	'Cegeka',
	'Cello',
	'Center for AI and Digital Policy',
	'Centre for European Policy Studies (CEPS)',
	'Centrum Nascholing Onderwijs CNO (UAntwerpen)',
	'Centrum voor Levende Talen (CLT)',
	'Centrum voor Planten Systeembiologie (PSB, VIB-UGent)',
	'Cerba Research',
	'CESPE - Centre of Excellence in Sustainable Pharmaceutical Engineering & Manufacturing',
	'CEVI Group',
	'Cevora',
	'Chaomatic',
	'CheatGPT',
	'Child Focus',
	'Christelijke Mutualiteit (CM)',
	'Cities of People',
	'CiTIUS (Centro Singular de Investigación en Tecnoloxías Intelixentes)',
	'CLARIAH-VL',
	'CLARIN-BE',
	'Climate Change AI',
	'Clusity',
	'CMAP, École Polytechnique',
	'CNRS',
	'Computer Vision Center, Universitat Autònoma de Barcelona',
	'Consono',
	'Convergence',
	'Council of Europe',
	'CPDP',
	'Creatief Schrijven',
	'Creative Lava',
	'Cronos.AI',
	'Crowell & Moring LLP',
	'Crunch Analytics',
	'CSEM (Conseil supérieur de l\'éducation aux médias)',
	'Cultuurconnect',
	'Customer Collective',
	'CVO Brussel',
	'CVPR',
	'CY Tech',
	'Cybersecurity Bites',
	'Cybersecurity Research Consortium',
	'Cybersecurity Vlaanderen',
	'Czech Technical Univesrity in Prague',
	'd-teach online school',
	'DAE-Research',
	'Data for Policy',
	'Data Protection Institute',
	'Data Science Institute (DSI, UHasselt)',
	'Database, Document and Content Management Research Group (DDCM, UGent)',
	'Datacamp',
	'Datacation',
	'Dataminded',
	'dataroots',
	'Datashift',
	'DATE 2022 Conference',
	'De AImbtenaar',
	'De Contentfabriek',
	'De Groote - De Man',
	'De Gruyter',
	'De Haagse Hogeschool',
	'De Nationale AI-Cursus',
	'De Standaard',
	'De Taalsector',
	'De Tijd',
	'De Woordnatie',
	'deBuren',
	'DeepL',
	'DeepLearn 2023 Winter',
	'DeepLearning.AI',
	'Deeplearning2023winter',
	'DeepSeek',
	'Degroof Petercam',
	'deJuristen',
	'Dell Technologies',
	'Deloitte',
	'Delta Translations',
	'Deontic',
	'Departement Computerwetenschappen KU Leuven',
	'Departement Informatie Technologie (INTEC, UGent)',
	'Dexia',
	'Dexr',
	'Dickerson et al.',
	'digiraf',
	'Digitaal Vlaanderen',
	'DIME (Disruptive Innovation in Medical Ethics, UGent)',
	'Dinobusters',
	'DLearning',
	'DNomads',
	'Docville',
	'Don Boscocollege Zwijnaarde',
	'dotdash.ai',
	'DPG Media België',
	'drAIve',
	'DTAI (Declarative Languages and Artificial Intelligence, KU Leuven)',
	'Durham University',
	'Dwengo',
	'e-taalent',
	'EAS Enterprise Estonia',
	'Easy.Brussels',
	'EBP (European Belgian Procurement)',
	'École centrale de Lyon',
	'École Universitaire Internationale, Research and Training on Peace and Security Studies',
	'Economische Raad Oost-Vlaanderen (Erov)',
	'EDIH - Energy in the Built Environment (EBE)',
	'EdTech Station',
	'edX',
	'Eekhout Academy',
	'Eén',
	'Effixis',
	'EHSAL Management School (EMS) (KU Leuven & Odisee)',
	'Eindhoven University of Technology',
	'EIT Digital',
	'EIT InnoEnergy',
	'EIT InnoEnergy',
	'Ekonomika Alumni (KU Leuven)',
	'ElevenLabs',
	'Elsevier',
	'EluciDATA Lab by SIRRIS',
	'Embuild',
	'Emma Legal',
	'ENAC, École Nationale de l\'Aviation Civile',
	'ENBIS (European Network for Business and Indsutrial Statistics)',
	'EnergyVille',
	'ENSAE Paris',
	'Enter Digital',
	'EOS Magazine',
	'EPCON',
	'EPFL Extension School',
	'ePotentia',
	'Erasmus Medical Centre (Erasmus MC)',
	'Erasmus University Rotterdam',
	'Erasmus+',
	'Erasmushogeschool Brussel',
	'ERC',
	'ERLNMYR',
	'ESF Vlaanderen',
	'Esri Belux',
	'ETH Zürich',
	'Ethics@KU Leuven',
	'Eubelius',
	'EuroCC Belgium',
	'Euroconsumers',
	'EUROCONTROL',
	'Europa Direct provincie Antwerpen',
	'European AI Office',
	'European Association for the Education of Adults (EAEA)',
	'European Cockpit Association',
	'European Commission',
	'European School Brussels II (EEBBII)',
	'European School Education Platform',
	'European Schoolnet',
	'European University Association (EUA)',
	'Europeana',
	'Europees Parlement',
	'Europese Commissie',
	'Everest Law',
	'Expert Academy',
	'Expertisecentrum Onderwijs en Leren (Thomas More)',
	'FAAR, het nonfictieboekenfestival in Oostende',
	'Faculteit Ingenieurswetenschappen KU Leuven',
	'Faculty of Organisation Studies (Slovenië)',
	'Fair Advantage',
	'FARI - AI for the Common Good Institute Brussels (ULB & VUB)',
	'FDJ SUEZ﻿﻿',
	'FEB Academy (UGent)',
	'Febelfin Academy',
	'FelixGPT',
	'FINN',
	'Finnian en Columba',
	'Finnish Center for Artificial Intelligence',
	'First AI\'d',
	'FLAMES',
	'Flanders AI EDIH Hub',
	'Flanders DC (District of Creativity)',
	'Flanders Investment & Trade',
	'Flanders Make',
	'Flanders Technology & Innovation (FTI)',
	'Flanders\' Care',
	'Flanders\' Food',
	'Flax - House of AI',
	'Fliki',
	'Flow Technical Communication',
	'Flowkify',
	'Fluves',
	'Flux50',
	'FOD Beleid & Ondersteuning',
	'FOD Economie',
	'FOD Financiën',
	'FOD Justitie',
	'Follow the Money',
	'Fonds Wetenschappelijk Onderzoek (FWO)',
	'Fontys Hogeschool',
	'Forschungszentrum Jülich',
	'Founderz',
	'Fourcast',
	'Frame - rehabilitation reframed, by Jessa',
	'FRS-FNRS (Fund for Scientific Research)',
	'Fruitsnacks',
	'Fujitsu',
	'Future Business Architects',
	'Future Learn',
	'Future Summits',
	'G2Speech',
	'Gaga',
	'Gamma Tech, Inc.',
	'Gandaius Academy (UGent)',
	'Geert Bollen',
	'Gemeente Rumst',
	'Georgetown University',
	'Georgia Institute of Technology',
	'Ghent Health Academy for Lifelong Learning (GHALL & UGent)',
	'GIM',
	'Glossy Branding Agency',
	'GLUON',
	'GMCOLAB',
	'Goethe-Institut Brussels',
	'Google',
	'Google Cloud',
	'Google DeepMind',
	'Gorilla',
	'Goverdson',
	'GPT Academy (UCLL Hogeschool)',
	'GreenTech Forum Brussels',
	'gt-omics',
	'Guberna',
	'GuruScan',
	'Habit of Improvement',
	'Hannah Arendt Instituut',
	'Happy 2 Change',
	'Harvard DtAK Lab',
	'Harvard Kennedy School',
	'Harvard University',
	'Health Intelligence Network.Gent (HINT.Gent)',
	'HealthHouse',
	'Het Facilitair Bedrijf (Vlaamse Overheid)',
	'Het Geluidshuis',
	'Het Klokhuis',
	'Hexagon Safety & Infrastructure',
	'HeyGen',
	'Hippo & Friends',
	'Hochschule Für Musik Und Tanz Köln',
	'Hochschule Wismar',
	'Hogeschool HOGENT',
	'Hogeschool PXL',
	'Hogeschool PXL',
	'Hogeschool Rotterdam (RUAS)',
	'Hogeschool VIVES... Howest Hogeschool',
	'Hub-C',
	'Hugging Face',
	'Humanities Academie (UGent)',
	'HumanX',
	'HumMingBird',
	'I Like Media',
	'I-care',
	'I-Leadership',
	'IAMD',
	'ianka fleerackers',
	'IBM',
	'IBM Research',
	'ICAI',
	'Icometrix',
	'ID Volk',
	'Idiap Research Institute',
	'IDLab (UGent-UAntwerpen-imec)',
	'ie-net',
	'IESE Business School',
	'IÉSEG School of Management',
	'IFORI',
	'IMD Business School',
	'imec',
	'ImmuneWatch',
	'Impact Connecting',
	'Imperial College London',
	'In The Pocket',
	'In4care',
	'Industriepartnerschap',
	'InfoFarm',
	'Infogram',
	'Infrabel',
	'INNOCOM',
	'Innovation Playground',
	'Institut de Mathématiques de Marseille',
	'Institute for Advanced Architecture of Catalonia',
	'Institute for Business Development (IFBD)',
	'Institute of Cognitive Sciences and Technologies Rome (ISTC-CNR)',
	'Institute of Mathematics Toulouse',
	'Instituto de Neurociencias de Alicante',
	'International Critical Control Rooms Alliance',
	'Interreg Vlaanderen-Nederland',
	'Intigriti',
	'Inzicht in AI',
	'IPCOS',
	'IRDTA',
	'IRIDIA (ULB)',
	'iSTEM',
	'IT1',
	'itec, imec onderzoeksgroep van KU Leuven',
	'ITS.be',
	'IViR - Universiteit van Amsterdam',
	'i~HD',
	'Janssen Pharmaceutical Company',
	'Jasper.ai',
	'Jessa Ziekenhuis',
	'Joe Public Belgium',
	'Johnson & Johnson',
	'Jonge Academie',
	'JournalismAi',
	'KANTL (Koninklijke Academie voor Nederlandse Taal en Letteren)',
	'Karel de Grote Hogeschool (KdG)',
	'Karlsruhe Institute of Technology',
	'Katholiek Onderwijs Vlaanderen',
	'KB (Nationale Bibliotheek van Nederland)',
	'KBC',
	'KBR',
	'Kenan-Flagler Business School',
	'Kenniscentrum Data & Maatschappij',
	'Kenniscentrum Digisprong',
	'Kennsicentrum Mediawijs',
	'KG3D (KU Leuven)',
	'King\'s College London',
	'Klasveren',
	'Knack',
	'Kom op tegen Kanker',
	'Koninklijk Conservatorium Brussel (Erasmushogeschool Brussel)',
	'Koninklijke Militaire School',
	'Koninklijke Musea voor Schone Kunsten van België (KMSKB)',
	'Konink8803;lijke Nederlandse Akademie voor Natuurwetenschappen',
	'Kortom',
	'KPMG',
	'Krea.AI',
	'KTH Royal Institute of Technology',
	'KU Leuven',
	'KU Leuven AI',
	'KU Leuven CiTiP',
	'KU Leuven Continue',
	'KU Leuven COSIC',
	'KU Leuven Digital Society Institute',
	'KU Leuven DistriNet',
	'KU Leuven ESAT PSI (Processing Speech and Images)',
	'KU Leuven ESAT STADIUS',
	'KU Leuven Instituut voor de Overheid',
	'KU Leuven Kulak',
	'KVAB',
	'LAAS-CNRS',
	'Laboratoire Ampère',
	'Laboratory for Chemical Technology (LCT), UGent',
	'Lady Margaret Hall',
	'Language and Translation Technology Team (LT3, UGent)',
	'Lannoo',
	'Lean Mean Learning Machine (LMLM)',
	'Learnable',
	'Learning Alliance',
	'Learning Bites',
	'Learning Bytes Festival',
	'Lees Simpel App',
	'LegalDirect',
	'Leonardo Interactive',
	'Leren.Hoe?Zo!',
	'Leuven Centre for Health Humanities (LCH²)',
	'Leuven Institute for Advanced Study (LIAS)',
	'Leuven Kankerinstituut (LKI)',
	'Leuven Mindgate',
	'Leuven Statistics Research Centre (Lstat, KU Leuven)',
	'Leuven Value Network',
	'Leuven.AI (KU Leuven)',
	'Leverhulme Centre for the Future of Intelligence (CFI)',
	'Lieven Scheire theatershow',
	'lifetech.brussels',
	'Like2Share',
	'LikeBirds',
	'LINC vzw',
	'LinkedIn',
	'LinkedIn Learning',
	'Linköping University',
	'Lockheed Martin',
	'Log!Ville',
	'London School of Economics (LSE)',
	'LUCA School of Arts',
	'Luma Labs',
	'Lumen5',
	'Maeve',
	'Maginative',
	'Magnific',
	'Maple Transactions',
	'March',
	'Materialise',
	'Mathworks',
	'Max Planck Institute for Mathematics',
	'Max Planck Institute for Mathematics in the Sciences',
	'Max Planck Institute for Software Systems',
	'Mayfair Village',
	'MbarQ',
	'Média animation',
	'Medialife',
	'Medica',
	'Medical Data Science',
	'MEDVIA',
	'Meertens Instituut',
	'Meespeeltuin',
	'Mensura',
	'Metamedica (UGent)',
	'MIAI Grenoble Alpes',
	'Microsoft',
	'Microsoft Research Lab, Cambridge',
	'Midjourney',
	'MinnaLearn',
	'Mistral AI',
	'MIT',
	'ML6',
	'MNRAI (Minnesota Responsible AI Institute)',
	'MolenGeek',
	'Monash University',
	'Mondai - House of AI',
	'movias',
	'Mpiris',
	'Mr. Franklin',
	'MTI²',
	'Munch',
	'Narhval',
	'NASA',
	'Nathalie De Graef',
	'National Education Lab AI (NOLAI)',
	'National Institute of Advanced Studies (India)',
	'NAVER LABS Europe',
	'NCOI Learning',
	'Nederlands Instituut voor Beeld & Geluid',
	'Nederlandse AI Coalitie',
	'Nemeon',
	'NEOMA Business School',
	'Nerdland',
	'Nerdland Festival',
	'Nerdland Ma2andoverzicht',
	'Netropolix',
	'Nextgenics',
	'Nexxtt.Health',
	'Nexxworks',
	'Nine Thirty Five',
	'NLP Town',
	'Noordhoff',
	'Northeastern University: College of Art, Media and Design (CAMD)',
	'Norwegian Open AI Lab',
	'Nova Reperta',
	'NOWJOBS',
	'NTGent',
	'Numbers',
	'Numeum & sustAIn.brussels',
	'Nvidia DLI',
	'NVT-net',
	'NXTGN',
	'nxtpro',
	'Odisee Hogeschool',
	'OECD',
	'On Track Lab',
	'Open & Agile Smart Cities',
	'Open Knowledge Belgium',
	'Open source',
	'OpenAI',
	'openSAP',
	'Opmerkelijk',
	'Orde der artsen (Ordomedic)',
	'Orsi Academy',
	'Orsi Academy',
	'ORTEC',
	'OSGG',
	'Owl Press',
	'Pandas',
	'Partena Professional',
	'Partnership for Advanced Computing in Europe (PRACE)',
	'PAULO Bestuursopleiding',
	'Perplexity',
	'Persado',
	'pharma.be',
	'PHÉRA',
	'Pinokio',
	'Pisa KDD Lab',
	'PIVO Vlaams-Brabant',
	'Plainsight',
	'Planet Tech Care & ISIT',
	'Platform Wiskunde Vlaanderen',
	'Player 1 Labs',
	'Polaris Digital',
	'Prebes',
	'Proficio',
	'ProRail',
	'Prosatt',
	'Provinciaal Onderwijs Antwerpen',
	'Provinciaal Onderwijs Vlaanderen (POV)',
	'Provincie Antwerpen',
	'Provincie Oost-Vlaanderen',
	'Provincie West-Vlaanderen',
	'Proximus',
	'PUC - KU Leuven Continue',
	'Puratos',
	'PXL-NeXT Hogeschool',
	'Python user group',
	'Python.exposed',
	'Qover',
	'Qual AI ty',
	'Queen\'s University',
	'Quetelet Society',
	'Raccoons',
	'Radboud Universiteit',
	'Radix',
	'RAILS, Robotics & AI Law Society',
	're.work',
	'Rebels in Peace',
	'redpencil.io',
	'REEDS',
	'Reimagine',
	'Reputations',
	'Rescope',
	'Rhite',
	'Rijksuniversiteit Groningen',
	'RITCS School of Arts',
	'RMMBR',
	'Robbe Wulgaert',
	'Robonext',
	'Rollins School of Public Health',
	'RoSa vzw',
	'Roularta Media Group',
	'Runway AI',
	'RWTH Aachen University',
	'Saarland University',
	'Samen Onderwijs Maken (SOM)',
	'Sanalex Advocaten',
	'Sapienza Universiteit van Rome',
	'SAS',
	'Savaco',
	'SBM',
	'Scholengemeenschap Groei',
	'Schoolmakers',
	'Schrijf.be',
	'Schrijfdokter',
	'SciComm Academy',
	'SciComm Academy - SciMingo',
	'Science Academy (UGent)',
	'Scivil',
	'sCooledu',
	'Scottish AI Alliance',
	'Scriptorij',
	'Scu76ola Normale Superiore di Pisa',
	'SeeMe.ai',
	'Seniornet Vlaanderen',
	'Sense about Science',
	'2Sentigrate',
	'SERV',
	'SevenYoken',
	'Seyhan Lee',
	'Sharpmountain',
	'Siemens',
	'Siemens Digital Industries Software',
	'Sievax',
	'SIGGIS (Spatial Intelligence Genuine & Generic IT Solutions)',
	'Signpost',
	'Sint-Lievenscollege Gent',
	'Sirius Legal',
	'Sirris',
	'SkillsTown',
	'Slovenian Artificial Intelligence Society',
	'Smarthealth',
	'SNT Brugge',
	'Sociale InnovatieFabriek',
	'Société Générale Group',
	'SOCN',
	'Soda',
	'Software Sustainability Institute',
	'SolidLab (imec, UGent, VUB & KU Leuven)',
	'Sol85vay Brussels School of Economics and Management',
	'Someflex',
	'Sony Computer Science Laboratory Paris',
	'Sopra Steria',
	'Sorbonne University',
	'Spinwise',
	'Springbok Agency',
	'Stability AI',
	'Stad Gent',
	'Stad Leuven',
	'Stad O2ostende',
	'Stanford Online',
	'Stanford University',
	'Starfish Consultancy',
	'Statik',
	'Statistiek Vlaanderen',
	'Steunpunt Onderwijs Limburg',
	'Stichting Merito',
	'Stichting overheidsopdrachten',
	'Strategic Vision Ventures',
	'studio909',
	'SUMSUM',
	'Superlinear',
	'sustAIn.Brussels',
	'Switch Laboratory (VIB & KU Leuven)',
	'SymphonyAI',
	'Syntra',
	'Syntra AB',
	'Syntra Brussel',
	'Syntra Midden-Vlaanderen',
	'Syntra West',
	'Taalunie',
	'TAILOR Netwerk',
	'Talentorium',
	'TalTech',
	'Tamara Gielen',
	'Tech-cursus.nl',
	'Technical University of Catalonia',
	'Technische Universität Berlin',
	'TechWolf',
	'TED',
	'TEDxKU Leuven',
	'Tel Aviv University',
	'Televic Education',
	'Televic GSP',
	'Televic Rail',
	'TeRoCo',
	'Textgain',
	'Textmetrics',
	'TEXTUA (UAntwerpen)',
	'The Alan Turing Institute',
	'The Beacon',
	'The Circle of Wellbeing',
	'The Girlfriend Experience (The GFEX)',
	'The Governors',
	'The GovLab',
	'The House of Coaching',
	'The House of Marketing',
	'THE Institute',
	'The Kosi Company',
	'The Learning Mindset Organization',
	'The Marketing Analytics Academy',
	'The Recruiters Academy',
	'The University of Warwick',
	'The Value Hub',
	'Theater aan Zee',
	'ThinkData Solutions, Inc',
	'Thomas More hogeschool',
	'Thomson Reuters',
	'thundr',
	'Tilburg University',
	'TomorrowLab',
	'Top of Your Game... Topsector Energie',
	'Toronto Metropolitan University',
	'Tracé Brussel',
	'Tracked.bio',
	'TRAIL Trusted AI Labs',
	'Training Network',
	'TRansformers',
	'Trendskout',
	'TRI-VIZOR',
	'Trinity Business School',
	'TU Delft',
	'UC Berkeley',
	'UC San Diego',
	'UCLA',
	'UCLL (Hogeschool UC Leuven-Limburg)',
	'UCLouvain',
	'UCLouvain Saint-Louis Brux2elles',
	'Udio',
	'UGain (UGent Academie voor Ingenieurs)',
	'UHasselt Doctoral Schools',
	'Uitgeverij Pelckmans',
	'Uitgeverij Plantyn',
	'ULB Knowledge Transfer Office (ULB-KTO)',
	'ULiège',
	'Ulysses AI',
	'UMANIQ',
	'Una',
	'Uncanny',
	'UNED',
	'UNESCO',
	'Unikoo',
	'Un2ilever',
	'Universidad Católica del Uruguay',
	'Univers2idade de Santiago de Compostela (USC)',
	'Universita Di Bologna (Unibo)',
	'Universitaire Stichting (Ethisch Forum)',
	'Universitat Pompeu Fabra Barcelona',
	'Université de Lille',
	'Université de Mons',
	'Université de Namur',
	'Université de Rennes 2',
	'Université de Toulouse',
	'Université des Femmes',
	'Université Libre De Bruxelles (ULB)',
	'Universiteit Antwerpen (AI)',
	'Universiteit Ant2werpen (UAntwerpen)',
	'Universiteit Gent (UGent)',
	'Universiteit Gent (UGent) (AI)',
	'Universiteit Hasselt (UHasselt)',
	'Universiteit Leiden',
	'Universiteit Maastricht',
	'Universiteit Twente',
	'Universiteit Utrecht',
	'Universiteit van Amsterdam',
	'Universiteit van Vlaanderen',
	'Universiteit van Wenen',
	'University College Dublin',
	'University College London',
	'University Hospital of Cologne',
	'University Institute of Lisbon (ISCTE)',
	'University Medical Center Groningen',
	'University of Bonn',
	'University of Bristol',
	'University of Cagliari',
	'University of California Santa Barbara',
	'University of California, Davis School of Law',
	'University of Chicago',
	'University of Copenhagen',
	'University of Debrecen',
	'University of Edinburgh',
	'University of Ferrara',
	'University of Genova',
	'University of Helsinki',
	'University of Illinois at Chicago (UIC)',
	'University of Leeds',
	'University of Michigan',
	'University of North Carolina at Chapel Hill',
	'University of Oslo',
	'University of Osnabrück',
	'University of Oxford',
	'University of Pisa',
	'University of Poitiers',
	'University of Southampton',
	'University of Southern Denmark',
	'University of Tartu',
	'University of Toronto',
	'University of Warsaw',
	'UNIZO',
	'Untaylored',
	'UNU-CRIS',
	'UP-TO-DATE WebDesign',
	'UPC KU Leuven',
	'UPM International Summer School',
	'Upthrust',
	'Uptune',
	'urban.brussels',
	'Utopia Aalst',
	'Utrecht Summer School',
	'Uwtekst.be',
	'UZ Brussel',
	'UZ Gent',
	'UZ Leuven',
	'VAIA',
	'Vakgroep Wijsbegeerte en Moraalwetenschap (UGent)',
	'Van Roey.be',
	'Vandewiele',
	'Vanguard Leadership',
	'VDAB',
	'VFB Academy',
	'VIB',
	'VIB.AI',
	'VIL - Empowering Logistics',
	'Vintecc',
	'Virtual Team Heroes',
	'Virtual Villains',
	'VITO Belgium',
	'VIVES Brugge Business School',
	'VIVO',
	'VKW Limburg',
	'Vlaams Agentschap Innoveren en Ond3ernemen (VLAIO)',
	'Vlaams AI-onderzoeksprogramma',
	'Vlaams Beleidsplan AI',
	'Vlaams Departement voor Werk Economie Wetenschap Innovatie en Sociale Economie (WEWIS)',
	'Vlaams Supercomputer Centrum',
	'Vlaams talenplatform',
	'Vlaamse Hogescholenraad (VLHORA)',
	'Vlaamse Overheid',
	'Vlaamse Vereniging van Journalisten (VVJ)',
	'Vlaamse Vereniging voor Steden en Gemeenten (VVSG)',
	'Vlaamse Verening voor Bibliotheek, Archief & Documentatie (VVBAD)',
	'Vlerick Business School',
	'VLIR',
	'VNG (Vereniging van Nederlandse Gemeenten)',
	'Voka (Vlaams netwerk van ondernemingen)',
	'Voka Antwerpen-Waasland',
	'Voka KvK Vlaams-Brabant',
	'VOV lerend netwerk',
	'Vrije Universiteit Amsterdam',
	'Vrije Universiteit Brussel (VUB)',
	'VRT',
	'VRT NWS',
	'VSC',
	'VTM',
	'VUB AI',
	'VUB Artificial Intelligence Lab',
	'VUB Brussels Privacy Hub (BPH)',
	'VUB CGIS (Cartography & GIS Research Group)',
	'VUB DIGI - Brussels Platform for Digital Humanities',
	'VUB Law, Science, Technology & Society Research Group (LSTS)',
	'VUB Vakgroep Wiskunde & Data Science (WIDS)',
	'VUB-imec Studies in Media, Innovation & Technology Research Group (SMIT)',
	'Vucable',
	'VVJ Academy (Vlaamse Vereniging van Journalisten)',
	'VVWL (Vlaamse Vereniging voor Wiskundeleraars)',
	'WAAI Design',
	'Webstrive',
	'Weights & Biases',
	'Weizenbaum Institut',
	'Wennovate',
	'West-Vlaams partnerschap Levenslang Leren',
	'Western University',
	'Wetenschappelijk Onderzoek- en Datacentrum (WODC)',
	'Whānau Branding',
	'Wharton School of the University of Pennsylvania',
	'Whitespectre',
	'WHU Otto Beisheim School of Management',
	'WIELS Centrum voor Hedendaagse Kunst',
	'Willemsfonds',
	'Winger Academy',
	'Winston Wolfe',
	'WISPER',
	'Wobby.ai',
	'Women in Data Science Belgium',
	'Wonka AI',
	'Woodwize',
	'WorkerPro',
	'WTCB-CSTC',
	'WVB-Consulting',
	'Yacoda',
	'Yamagata Europe',
	'YouReCa (KU Leuven)',
	'ZAVO',
	'Zeeuwse Onderwijskolom',
	'Zenspiratie',
	'Zero to Singularity',
	'Zeticon',
	'Zoom'
];

export const priceLevelsEnum = ['Gratis', '€0 - 100', '€100 - 500', '€500+', 'Prijs op aanvraag'] as const;
export const priceLevels: string[] = [...priceLevelsEnum];

export const afterCourseGoalsEnum = ['geïnspireerd zijn', 'met een (specifieke) AI-tool werken', 'een kader voor AI creëren', 'AI technisch implementeren', 'mezelf specialiseren'] as const;
export const afterCourseGoals: string [] = [...afterCourseGoalsEnum];

export const ethicDomainsEnum = ['Menselijke controle', 'Technische robuustheid & veiligheid', 'Privacy & databeheer', 'Transparantie', 'Diversiteit & rechtvaardigheid', 'Maatschappelijk welzijn', 'Verantwoording'] as const;
export const ethicDomains: string [] = [...ethicDomainsEnum];

export const certificatesEnum = ['Aanwezigheidsattest', 'Certificaat', 'Micro-credential', 'Postgraduaat', 'Ander'] as const;
export const certificates: string [] = [...certificatesEnum];

export const knowledgeLevelsEnum = ['kennismaken met AI', 'met AI aan de slag', 'mijn AI-kennis upgraden'] as const;
export const knowledgeLevels: string [] = [...knowledgeLevelsEnum];

export const scopeOfApplicationsEnum = ['Architectuur & bouw', 'Business, management & HR', 'Communicatie, media & telecom', 'Computerwetenschappen & IT', 'Energie & nutvoorzieningen', 'Filosofie, ethiek & moraalwetenschappen', 'Financiën, fiscaliteit & verzekeringen', 'Gezondheidszorg, biomedische wetenschappen & sport', 'Industrie & logistiek', 'Kunst, cultuur & sociale wetenschappen', 'Landbouw, natuur & milieu', 'Hoger onderwijs & onderzoek', 'Marketing & economie', 'Mobiliteit & ruimtelijke ordening', 'Onderwijs', 'Overheid & bestuur', 'Recht & handhaving', 'Retail', 'Voedingsindustrie & horeca', 'Over alle disciplines heen (algemeen AI)'] as const;
export const scopeOfApplications: string [] = [...scopeOfApplicationsEnum];

export const languagesEnum = ['Nederlands', 'Engels', 'Nederlands & Engels', 'Anders'] as const;
export const languages: string [] = [...languagesEnum];

export const locationZonesEnum = ['Online', 'Jij kiest (in-company)', 'Antwerpen', 'Brugge', 'Brussel', 'Geel', 'Gent', 'Hasselt', 'Kortrijk', 'Leuven', 'Mechelen', 'Vlaanderen', 'Franstalig België', 'Buitenland'] as const;
export const locationZones: string [] = [...locationZonesEnum];